export const snapshotV1 = {
  schema_version: 1,
  generated_at: "2026-07-25T03:00:00Z",
  source: "local-runtime",
  markets: [
    { market_id: "kr", label: "한국", local_time: "2026-07-25T12:00:00+09:00", state: "closed" },
    { market_id: "us", label: "미국", local_time: "2026-07-24T23:00:00-04:00", state: "closed" },
  ],
  forward: {
    session_date: "2026-07-24",
    eligible: false,
    ranking_cycles: 1,
    watch_cycles: 1,
    failed_watch_cycles: 0,
    read_retries: 0,
    read_retry_failures: 0,
    candidate_input_cycles: 1,
    candidate_inputs: 0,
    recommendations: 0,
    blockers: [],
    incidents: [],
  },
  agents: [],
  recommendations: [],
  signals: [],
  research: { status: "unavailable", session_date: "2026-07-24", summary: "연구 권위 없음" },
  account: {
    status: "unavailable",
    session_date: "2026-07-24",
    observed_at: null,
    currency: "USD",
    equity: null,
    daily_pnl: null,
    realized_pnl: null,
    unrealized_pnl: null,
    planned_open_risk: null,
    open_positions: 0,
    open_orders: 0,
  },
} as const;
