from __future__ import annotations

from typing import Final

DERIVED_STRATEGY_SOURCE: Final = (
    "def _market_allows(patch, bars):\n"
    "    count = patch['confirmation_bars']\n"
    "    if len(bars) < count:\n"
    "        return False\n"
    "    selected = bars[-count:]\n"
    "    if patch['rule'] == 'trend_alignment':\n"
    "        return all(left['close'] <= right['close'] for left, right in zip(selected, selected[1:]))\n"
    "    ranges = [item['high'] - item['low'] for item in selected]\n"
    "    return all(left >= right for left, right in zip(ranges, ranges[1:]))\n"
    "def _theme_allows(patch, candidate):\n"
    "    limit = 30 if patch['timing_window'] == 'opening_30_minutes' else 60\n"
    "    return candidate['minutes_from_open'] <= limit and "
    "candidate['theme_catalyst_count'] >= patch['minimum_catalyst_count']\n"
    "def _catalyst_allows(patch, bar, candidate):\n"
    "    fresh = candidate['catalyst_age_minutes'] <= patch['maximum_age_minutes']\n"
    "    if patch['rule'] == 'freshness_first':\n"
    "        return fresh\n"
    "    return fresh and bool(candidate['catalyst']) and candidate['catalyst'] == bar['catalyst']\n"
    "def _leader_allows(patch, candidate):\n"
    "    scores = {'relative_volume': min(candidate['relative_volume'] / 5.0, 1.0), "
    "'dollar_volume': min(candidate['cumulative_dollar_volume'] / 10000000.0, 1.0), "
    "'gap_strength': min(abs(candidate['gap_pct']) / 10.0, 1.0)}\n"
    "    return scores[patch['feature']] >= patch['weight_bps'] / 10000.0\n"
    "def _flow_allows(patch, bars, candidate):\n"
    "    count = patch['confirmation_bars']\n"
    "    if len(bars) < count:\n"
    "        return False\n"
    "    selected = bars[-count:]\n"
    "    if patch['rule'] == 'volume_confirmation':\n"
    "        return all(left['volume'] <= right['volume'] for left, right in zip(selected, selected[1:]))\n"
    "    return all(left['spread_bps'] >= right['spread_bps'] "
    "for left, right in zip(selected, selected[1:])) and "
    "candidate['spread_bps'] <= selected[-1]['spread_bps']\n"
    "def _execution_allows(patch, candidate):\n"
    "    if candidate['execution_review_sessions'] < patch['review_window_sessions']:\n"
    "        return False\n"
    "    metric = candidate['estimated_slippage_bps'] if "
    "patch['rule'] == 'slippage_attribution' else candidate['fill_quality_bps']\n"
    "    return metric <= 20.0\n"
    "def _entry_patch(patch, signal):\n"
    "    changed = dict(signal)\n"
    "    risk = signal['entry'] - signal['stop']\n"
    "    fraction = patch['confirmation_bars'] * 0.05\n"
    "    if patch['rule'] == 'breakout_confirmation':\n"
    "        changed['entry'] = signal['entry'] + risk * fraction\n"
    "    else:\n"
    "        changed['entry'] = max(signal['stop'] + risk * 0.1, signal['entry'] - risk * fraction)\n"
    "    return changed\n"
    "def _exit_patch(patch, signal, bars):\n"
    "    changed = dict(signal)\n"
    "    risk = signal['entry'] - signal['stop']\n"
    "    window = patch['trailing_window_bars']\n"
    "    if patch['rule'] == 'r_multiple_targets':\n"
    "        changed['stop'] = signal['entry'] - risk * (1.0 + window * 0.02)\n"
    "    else:\n"
    "        structure = min(item['low'] for item in bars[-window:])\n"
    "        changed['stop'] = min(signal['entry'] - risk * 0.1, max(signal['stop'], structure))\n"
    "    return changed\n"
    "def create_strategy(context):\n"
    "    parent_strategy = _PARENT_CREATE_STRATEGY(context)\n"
    "    class DerivedStrategy:\n"
    "        def __init__(self):\n"
    "            self._bars = []\n"
    "        def observe(self, bar, candidate):\n"
    "            self._bars.append(bar)\n"
    "            self._bars = self._bars[-20:]\n"
    "            inherited = parent_strategy.observe(bar, candidate)\n"
    "            if inherited is None:\n"
    "                return None\n"
    "            kind = _PATCH['kind']\n"
    "            if kind == 'entry_policy':\n"
    "                return _entry_patch(_PATCH, inherited)\n"
    "            if kind == 'exit_policy':\n"
    "                return _exit_patch(_PATCH, inherited, self._bars)\n"
    "            if candidate is None:\n"
    "                return None\n"
    "            allowed = (_market_allows(_PATCH, self._bars) if kind == 'market_regime_policy' else "
    "_theme_allows(_PATCH, candidate) if kind == 'theme_selection_policy' else "
    "_catalyst_allows(_PATCH, bar, candidate) if kind == 'catalyst_interpretation_policy' else "
    "_leader_allows(_PATCH, candidate) if kind == 'leader_ranking_policy' else "
    "_flow_allows(_PATCH, self._bars, candidate) if kind == 'flow_interpretation_policy' else "
    "_execution_allows(_PATCH, candidate))\n"
    "            return inherited if allowed else None\n"
    "    return DerivedStrategy()\n"
)


__all__ = ("DERIVED_STRATEGY_SOURCE",)
